package at.ac.tuwien.iter.services;

import java.util.Collection;

import at.ac.tuwien.iter.data.Test;
import at.ac.tuwien.iter.data.TestResult;

public interface TestSuiteEvolver {

	/**
	 * Return a Collection of tests to be run. The tests are generated by
	 * evolving the actual test suite
	 * 
	 * @param testSuite
	 * @return
	 */
	public Collection<Test> evolveTestSuite(Collection<Test> testSuite,
			Collection<TestResult> testResults);
}
